apiVersion: v1
kind: Service
metadata:
  name: web-app-test-1
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    com.docker.project: web-app-test-1
  type: LoadBalancer
status:
  loadBalancer: {}
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.project: web-app-test-1
  name: web-app-test-1
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: web-app-test-1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: web-app-test-1
    spec:
      containers:
      - image: rozanski/testrepo1
        name: web-app-test-1
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}